import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Guard: the committed browser data module (web/data/handoff.js) must never silently
// drift from the real witnessed receipt (examples/live-loop/handoff.json — the canonical
// receipt that came through the live loop). If they diverge, the demo page would tell a
// different story than the actual receipt rules — exactly what Lyhna exists to prevent.
// Regenerate with `node web/build-data.mjs`.

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");
const jsonPath = path.join(root, "examples", "live-loop", "handoff.json");
const dataJsPath = path.join(root, "web", "data", "handoff.js");

test("web/data/handoff.js exactly matches examples/live-loop/handoff.json", () => {
  const json = JSON.parse(readFileSync(jsonPath, "utf8"));
  const dataJs = readFileSync(dataJsPath, "utf8");

  // Extract the embedded object literal: everything between the first `{` and the
  // final `};` (the assignment to window.LYHNA_HANDOFF).
  const start = dataJs.indexOf("window.LYHNA_HANDOFF =");
  assert.ok(start >= 0, "web/data/handoff.js must assign window.LYHNA_HANDOFF");

  const eq = dataJs.indexOf("=", start);
  const semi = dataJs.lastIndexOf("};");
  assert.ok(semi > eq, "web/data/handoff.js must end the assignment with `};`");

  const objectLiteral = dataJs.slice(eq + 1, semi + 1).trim();
  const embedded = JSON.parse(objectLiteral);

  assert.deepEqual(
    embedded,
    json,
    "web/data/handoff.js is out of sync with handoff.json — run `node web/build-data.mjs`"
  );

  // Also assert the byte-for-byte serialization matches what the generator would write,
  // so formatting drift is caught too. Line endings are normalized to LF first: a Windows
  // checkout (git autocrlf) can store handoff.js with CRLF, which is a platform artifact —
  // not receipt/content/formatting drift. Every meaningful difference (banner, indentation,
  // spacing, content) is still caught after normalization.
  const toLf = (s) => s.replace(/\r\n/g, "\n");
  const expected =
    "// AUTO-GENERATED by web/build-data.mjs from examples/live-loop/handoff.json.\n" +
    "// Do not edit by hand. Run `node web/build-data.mjs` to regenerate.\n" +
    `window.LYHNA_HANDOFF = ${JSON.stringify(json, null, 2)};\n`;

  assert.equal(
    toLf(dataJs),
    toLf(expected),
    "web/data/handoff.js content differs from generator output — run `node web/build-data.mjs`"
  );
});
