#!/usr/bin/env node
// build-data.mjs — zero-dep generator.
// Reads the committed witnessed handoff and writes a browser-loadable JS module
// (window.LYHNA_HANDOFF = <the JSON>) so the static demo page can render the
// EXACT receipt even when opened over file:// (where fetch() is unreliable).
//
// Run: node web/build-data.mjs
// The output web/data/handoff.js is committed and kept in sync via test/web-data.test.mjs.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const srcPath = path.join(here, "..", "examples", "hermes-zapier", "handoff.json");
const outDir = path.join(here, "data");
const outPath = path.join(outDir, "handoff.js");

// Re-serialize through JSON.parse/stringify so the embedded object is canonical
// and stable (2-space indent), and so a malformed source fails loudly here.
const raw = readFileSync(srcPath, "utf8");
const data = JSON.parse(raw);
const pretty = JSON.stringify(data, null, 2);

const banner =
  "// AUTO-GENERATED by web/build-data.mjs from examples/hermes-zapier/handoff.json.\n" +
  "// Do not edit by hand. Run `node web/build-data.mjs` to regenerate.\n";

const contents = `${banner}window.LYHNA_HANDOFF = ${pretty};\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, contents, "utf8");

console.log(`Wrote ${path.relative(path.join(here, ".."), outPath)} from examples/hermes-zapier/handoff.json`);
